services:
  postgres:
    environment:
      - "PGBOUNCER_CONFIGURATION=enabled"

    configs:
      - source: pgbouncer.ini
        target: /run/pgbouncer/pgbouncer.ini

configs:
  pgbouncer.ini:
    file: services/pgbouncer/pgbouncer.ini
