x-logging: &x-default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  loadbalancer:
    image: haproxytech/haproxy-alpine:latest
    networks:
      - postgres_default
    ports:
      - 5000:5000 # pgsql_master
      - 5001:5001 # pgsql_replicas
      - 8008:8008 # pgsql_spilo_api
      - 8404:8404 # stats
    configs:
      - source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    deploy:
      replicas: ${PGSQL_LOADBALANCER_REPLICAS:-3}
    logging: *x-default-logging

  postgres:
    deploy:
      endpoint_mode: dnsrr

configs:
  haproxy.cfg:
    file: services/haproxy/haproxy.cfg
